server:
  port: 8001

dubbo:
  application:
    name: provider-product   # 服务名称
  registry: # 注册中心
    protocol: zookeeper
    address: baseCentos:2181
  protocol: # 服务端口
    port: 28800


spring:
  # mysql 相关配置
  # 数据源配置，只需要在服务启动的工程中配置，也就是provider以及consumer中配置
  datasource:
    url: jdbc:mysql://baseCentos:3306/shop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #    url: jdbc:mysql://192.168.206.130:3306/shop
    username: root
    password: 123456

