server:
  port: 9001

dubbo:
  application:
    name: consumer-product
  registry:
    protocol: zookeeper
    address: baseCentos:2181


spring:
  # mysql 相关配置
  # 数据源配置，只需要在服务启动的工程中配置，也就是provider以及consumer中配置
  datasource:
    url: jdbc:mysql://baseCentos:3306/shop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #    url: jdbc:mysql://192.168.206.130:3306/shop
    username: root
    password: 123456

  # spring boot rabbitmq 相关配置
  rabbitmq:
    host: 192.168.157.128
    port: 5672
    username: sda1
    password: 123456
    virtual-host: sda1_mq

# fastdfs配置
fdfs:
  so-timeout: 1500 # 读取时间
  connect-timeout: 600  # 链接超时时间
  pool: # 连接池
    jmx-enabled: false
  thumb-image:  # 缩略图
    width: 100
    height: 100
  tracker-list: baseCentos:22122   # 跟踪器地址

filePath:
  service: http://baseCentos/



